### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by lansheng228** [CyberMiles/travis#11]
https://travis.readthedocs.io/en/latest/getting-started.html#build-from-source
我按照这个文档编译，报如下错误。
请问是为什么？   （我用的libeni-1.3.2， 我用的go1.11， ubuntu16.04）
谢谢。

$ make all
--> Installing tools
go get github.com/Masterminds/glide
--> Tools installed successfully
glide install
[WARN]	Lock file may be out of date. Hash check of YAML failed. You may need to run 'update'
[INFO]	Downloading dependencies. Please wait...
[INFO]	--> Found desired version locally github.com/aristanetworks/goarista 59944ff78bc1de686b0aba1444dfd380f48f03d4!
[INFO]	--> Found desired version locally github.com/beorn7/perks 3a771d992973f24aa725d07868b467d1ddfceafb!
[INFO]	--> Found desired version locally github.com/bgentry/speakeasy 4aabc24848ce5fd31929f7d1e4ea74d3709c14cd!
[INFO]	--> Found desired version locally github.com/btcsuite/btcd 86fed781132ac890ee03e906e4ecd5d6fa180c64!
[INFO]	--> Found desired version locally github.com/BurntSushi/toml a368813c5e648fee92e5f6c30e3944ff9d5e8895!
[INFO]	--> Found desired version locally github.com/davecgh/go-spew 346938d642f2ec3594ed81d874461961cd0faa76!
[INFO]	--> Found desired version locally github.com/ebuchman/fail-test 95f809107225be108efcf10a3509e4ea6ceef3c4!
[INFO]	--> Found desired version locally github.com/edsrzf/mmap-go 0bce6a6887123b67a60366d2c9fe2dfb74289d2e!
[INFO]	--> Found desired version locally github.com/elastic/gosigar 37f05ff46ffa7a825d1b24cf2b62d4a4c1a9d2e8!
[INFO]	--> Found desired version locally github.com/ethereum/go-ethereum 8b72416b64a0717b031e6efaebf12bbe97df1a2e!
[INFO]	--> Found desired version locally github.com/fatih/color 2d684516a8861da43017284349b7e303e809ac21!
[INFO]	--> Found desired version locally github.com/fjl/memsize f6d5545993d68e9e42df43eb57958f898dea3623!
[INFO]	--> Found desired version locally github.com/fsnotify/fsnotify c2828203cd70a50dcccfb2761f8b1f8ceef9a8e9!
[INFO]	--> Found desired version locally github.com/go-kit/kit ca4112baa34cb55091301bdc13b1420a122b1b9e!
[INFO]	--> Found desired version locally github.com/go-logfmt/logfmt 390ab7935ee28ec6b286364bba9b4dd6410cb3d5!
[INFO]	--> Found desired version locally github.com/go-ole/go-ole 7a0fa49edf48165190530c675167e2f319a05268!
[INFO]	--> Found desired version locally github.com/go-stack/stack 259ab82a6cad3992b4e21ff5cac294ccb06474bc!
[INFO]	--> Found desired version locally github.com/gogo/protobuf 1adfc126b41513cc696b209667c8656ea7aac67c!
[INFO]	--> Found desired version locally github.com/golang/protobuf b4deda0973fb4c70b50d226b1af49f3da59f5265!
[INFO]	--> Found desired version locally github.com/golang/snappy 2e65f85255dbc3072edf28d6b5b8efc472979f5a!
[INFO]	--> Found desired version locally github.com/gorilla/websocket 5ed622c449da6d44c3c8329331ff47a9e5844f71!
[INFO]	--> Found desired version locally github.com/hashicorp/golang-lru 0fb14efe8c47ae851c0034ed7a448854d3d34cf3!
[INFO]	--> Found desired version locally github.com/hashicorp/hcl ef8a98b0bbce4a65b5aa4c368430a80ddc533168!
[INFO]	--> Found desired version locally github.com/huin/goupnp 1395d1447324cbea88d249fbfcfd70ea878fdfca!
[INFO]	--> Found desired version locally github.com/inconshreveable/mousetrap 76626ae9c91c4f2a10f34cad8ce83ea42c93bb75!
[INFO]	--> Found desired version locally github.com/influxdata/influxdb bed425313b399096d5a35b0c65c6a9e4270474f5!
[INFO]	--> Found desired version locally github.com/jackpal/go-nat-pmp 28a68d0c24adce1da43f8df6a57340909ecd7fdd!
[INFO]	--> Found desired version locally github.com/jmhodges/levigo c42d9e0ca023e2198120196f842701bb4c55d7b9!
[INFO]	--> Found desired version locally github.com/karalabe/hid 2b4488a37358b7283de4f9622553e85ebbe73125!
[INFO]	--> Found desired version locally github.com/kr/logfmt b84e30acd515aadc4b783ad4ff83aff3299bdfe0!
[INFO]	--> Found desired version locally github.com/magiconair/properties c2353362d570a7bfa228149c62842019201cfb71!
[INFO]	--> Found desired version locally github.com/mattn/go-colorable efa589957cd060542a26d2dd7832fd6a6c6c3ade!
[INFO]	--> Found desired version locally github.com/mattn/go-isatty 6ca4dbf54d38eea1a992b3c722a76a5d1c4cb25c!
[INFO]	--> Found desired version locally github.com/mattn/go-runewidth ce7b0b5c7b45a81508558cd1dba6bb1e4ddb51bb!
[INFO]	--> Found desired version locally github.com/mattn/go-sqlite3 6c771bb9887719704b210e87e934f08be014bdb1!
[INFO]	--> Found desired version locally github.com/matttproud/golang_protobuf_extensions 3247c84500bff8d9fb6d579d800f20b3e091582c!
[INFO]	--> Found desired version locally github.com/mitchellh/mapstructure bb74f1db0675b241733089d5a1faa5dd8b0ef57b!
[INFO]	--> Found desired version locally github.com/pborman/uuid c65b2f87fee37d1c7854c9164a450713c28d50cd!
[INFO]	--> Found desired version locally github.com/pelletier/go-toml c01d1270ff3e442a8a57cddc1c92dc1138598194!
[INFO]	--> Found desired version locally github.com/peterh/liner 80ce870644db1b043e8dc2cf836bde5c347e2701!
[INFO]	--> Found desired version locally github.com/pkg/errors 645ef00459ed84a119197bfb8d8205042c6df63d!
[INFO]	--> Found desired version locally github.com/prometheus/client_golang c5b7fccd204277076155f10851dad72b76a49317!
[INFO]	--> Found desired version locally github.com/prometheus/client_model 99fa1f4be8e564e8a6b613da7fa6f46c9edafc6c!
[INFO]	--> Found desired version locally github.com/prometheus/common e4aa40a9169a88835b849a6efb71e05dc04b88f0!
[INFO]	--> Found desired version locally github.com/prometheus/procfs 54d17b57dd7d4a3aa092476596b3f8a933bde349!
[INFO]	--> Found desired version locally github.com/prometheus/prometheus 0a74f98628a0463dddc90528220c94de5032d1a0!
[INFO]	--> Found desired version locally github.com/rcrowley/go-metrics e2704e165165ec55d062f5919b4b29494e9fa790!
[INFO]	--> Found desired version locally github.com/rjeczalik/notify d152f3ce359a5464dc41e84a8919fc67e55bbbf0!
[INFO]	--> Found desired version locally github.com/robertkrimen/otto 15f95af6e78dcd2030d8195a138bd88d4f403546!
[INFO]	--> Found desired version locally github.com/rs/cors 694cf2ad010fcf91ee35161f5bfdad8f42ed1b9a!
[INFO]	--> Found desired version locally github.com/spf13/afero 787d034dfe70e44075ccc060d346146ef53270ad!
[INFO]	--> Found desired version locally github.com/spf13/cast 8965335b8c7107321228e3e3702cab9832751bac!
[INFO]	--> Found desired version locally github.com/spf13/cobra 1e58aa3361fd650121dceeedc399e7189c05674a!
[INFO]	--> Found desired version locally github.com/spf13/jwalterweatherman 7c0cea34c8ece3fbeb2b27ab9b59511d360fb394!
[INFO]	--> Found desired version locally github.com/spf13/pflag 3ebe029320b2676d667ae88da602a5f854788a8a!
[INFO]	--> Found desired version locally github.com/spf13/viper 15738813a09db5c8e5b60a19d67d3f9bd38da3a4!
[INFO]	--> Found desired version locally github.com/StackExchange/wmi cdffdb33acae0e14efff2628f9bae377b597840e!
[INFO]	--> Found desired version locally github.com/syndtr/goleveldb e2150783cd35f5b607daca48afd8c57ec54cc995!
[INFO]	--> Found desired version locally github.com/tendermint/ed25519 d8387025d2b9d158cf4efb07e7ebf814bcce2057!
[INFO]	--> Found desired version locally github.com/tendermint/go-amino 2106ca61d91029c931fd54968c2bb02dc96b1412!
[INFO]	--> Found desired version locally github.com/tendermint/go-wire fd33313baedb08fffafa3837994d3f02a6587baf!
[INFO]	--> Found desired version locally github.com/tendermint/iavl 35f66e53d9b01e83b30de68b931f54b2477a94c9!
[INFO]	--> Found desired version locally github.com/tendermint/tendermint dfa9a9a30a666132425b29454e90a472aa579a48!
[INFO]	--> Found desired version locally golang.org/x/crypto c3a3ad6d03f7a915c0f7e194b7152974bb73d287!
[INFO]	--> Found desired version locally golang.org/x/net 92b859f39abd2d91a854c9f9c4621b2f5054a92d!
[INFO]	--> Found desired version locally golang.org/x/sync 1d60e4601c6fd243af51cc01ddf169918a5407ca!
[INFO]	--> Found desired version locally golang.org/x/sys d8e400bc7db4870d786864138af681469693d18c!
[INFO]	--> Found desired version locally golang.org/x/text f21a4dfb5e38f5895301dc265a8def02365cc3d0!
[INFO]	--> Found desired version locally google.golang.org/genproto ff3583edef7de132f219f0efc00e097cabcc0ec0!
[INFO]	--> Found desired version locally google.golang.org/grpc 168a6198bcb0ef175f7dacec0b8691fc141dc9b8!
[INFO]	--> Found desired version locally gopkg.in/fatih/set.v0 2c768e3c5489976167bfc42b5c7c92ca783f4389!
[INFO]	--> Found desired version locally gopkg.in/karalabe/cookiejar.v2 8dcd6a7f4951f6ff3ee9cbb919a06d8925822e57!
[INFO]	--> Found desired version locally gopkg.in/natefinch/npipe.v2 c1b8fa8bdccecb0b8db834ee0b92fdbcfa606dd6!
[INFO]	--> Found desired version locally gopkg.in/olebedev/go-duktape.v3 abf0ba0be5d5d36b1f9266463cc320b9a5ab224e!
[INFO]	--> Found desired version locally gopkg.in/sourcemap.v1 6e83acea0053641eff084973fee085f0c193c61a!
[INFO]	--> Found desired version locally gopkg.in/urfave/cli.v1 cfb38830724cc34fedffe9a2a29fb54fa9169cd1!
[INFO]	--> Found desired version locally gopkg.in/yaml.v2 5420a8b6744d3b0345ab293f6fcba19c978f1183!
[INFO]	--> Found desired version locally github.com/pmezard/go-difflib 792786c7400a136282c1664665ae0a8db921c6c2!
[INFO]	--> Found desired version locally github.com/stretchr/testify f35b8ab0b5a2cef36673838d662e249dd9c94686!
[INFO]	Setting references.
[INFO]	--> Setting version for github.com/aristanetworks/goarista to 59944ff78bc1de686b0aba1444dfd380f48f03d4.
[INFO]	--> Setting version for github.com/fatih/color to 2d684516a8861da43017284349b7e303e809ac21.
[INFO]	--> Setting version for github.com/go-kit/kit to ca4112baa34cb55091301bdc13b1420a122b1b9e.
[INFO]	--> Setting version for github.com/ethereum/go-ethereum to 8b72416b64a0717b031e6efaebf12bbe97df1a2e.
[INFO]	--> Setting version for github.com/fjl/memsize to f6d5545993d68e9e42df43eb57958f898dea3623.
[INFO]	--> Setting version for github.com/elastic/gosigar to 37f05ff46ffa7a825d1b24cf2b62d4a4c1a9d2e8.
[INFO]	--> Setting version for github.com/ebuchman/fail-test to 95f809107225be108efcf10a3509e4ea6ceef3c4.
[INFO]	--> Setting version for github.com/btcsuite/btcd to 86fed781132ac890ee03e906e4ecd5d6fa180c64.
[INFO]	--> Setting version for github.com/edsrzf/mmap-go to 0bce6a6887123b67a60366d2c9fe2dfb74289d2e.
[INFO]	--> Setting version for github.com/go-logfmt/logfmt to 390ab7935ee28ec6b286364bba9b4dd6410cb3d5.
[INFO]	--> Setting version for github.com/bgentry/speakeasy to 4aabc24848ce5fd31929f7d1e4ea74d3709c14cd.
[INFO]	--> Setting version for github.com/davecgh/go-spew to 346938d642f2ec3594ed81d874461961cd0faa76.
[INFO]	--> Setting version for github.com/BurntSushi/toml to a368813c5e648fee92e5f6c30e3944ff9d5e8895.
[INFO]	--> Setting version for github.com/golang/protobuf to b4deda0973fb4c70b50d226b1af49f3da59f5265.
[INFO]	--> Setting version for github.com/gogo/protobuf to 1adfc126b41513cc696b209667c8656ea7aac67c.
[INFO]	--> Setting version for github.com/go-ole/go-ole to 7a0fa49edf48165190530c675167e2f319a05268.
[INFO]	--> Setting version for github.com/fsnotify/fsnotify to c2828203cd70a50dcccfb2761f8b1f8ceef9a8e9.
[INFO]	--> Setting version for github.com/go-stack/stack to 259ab82a6cad3992b4e21ff5cac294ccb06474bc.
[INFO]	--> Setting version for github.com/golang/snappy to 2e65f85255dbc3072edf28d6b5b8efc472979f5a.
[INFO]	--> Setting version for github.com/beorn7/perks to 3a771d992973f24aa725d07868b467d1ddfceafb.
[INFO]	--> Setting version for github.com/gorilla/websocket to 5ed622c449da6d44c3c8329331ff47a9e5844f71.
[INFO]	--> Setting version for github.com/hashicorp/golang-lru to 0fb14efe8c47ae851c0034ed7a448854d3d34cf3.
[INFO]	--> Setting version for github.com/hashicorp/hcl to ef8a98b0bbce4a65b5aa4c368430a80ddc533168.
[INFO]	--> Setting version for github.com/inconshreveable/mousetrap to 76626ae9c91c4f2a10f34cad8ce83ea42c93bb75.
[INFO]	--> Setting version for github.com/influxdata/influxdb to bed425313b399096d5a35b0c65c6a9e4270474f5.
[INFO]	--> Setting version for github.com/jackpal/go-nat-pmp to 28a68d0c24adce1da43f8df6a57340909ecd7fdd.
[INFO]	--> Setting version for github.com/jmhodges/levigo to c42d9e0ca023e2198120196f842701bb4c55d7b9.
[INFO]	--> Setting version for github.com/karalabe/hid to 2b4488a37358b7283de4f9622553e85ebbe73125.
[INFO]	--> Setting version for github.com/huin/goupnp to 1395d1447324cbea88d249fbfcfd70ea878fdfca.
[INFO]	--> Setting version for github.com/kr/logfmt to b84e30acd515aadc4b783ad4ff83aff3299bdfe0.
[INFO]	--> Setting version for github.com/magiconair/properties to c2353362d570a7bfa228149c62842019201cfb71.
[INFO]	--> Setting version for github.com/mattn/go-colorable to efa589957cd060542a26d2dd7832fd6a6c6c3ade.
[INFO]	--> Setting version for github.com/mattn/go-isatty to 6ca4dbf54d38eea1a992b3c722a76a5d1c4cb25c.
[INFO]	--> Setting version for github.com/mattn/go-runewidth to ce7b0b5c7b45a81508558cd1dba6bb1e4ddb51bb.
[INFO]	--> Setting version for github.com/mattn/go-sqlite3 to 6c771bb9887719704b210e87e934f08be014bdb1.
[INFO]	--> Setting version for github.com/matttproud/golang_protobuf_extensions to 3247c84500bff8d9fb6d579d800f20b3e091582c.
[INFO]	--> Setting version for github.com/mitchellh/mapstructure to bb74f1db0675b241733089d5a1faa5dd8b0ef57b.
[INFO]	--> Setting version for github.com/pborman/uuid to c65b2f87fee37d1c7854c9164a450713c28d50cd.
[INFO]	--> Setting version for github.com/pelletier/go-toml to c01d1270ff3e442a8a57cddc1c92dc1138598194.
[INFO]	--> Setting version for github.com/peterh/liner to 80ce870644db1b043e8dc2cf836bde5c347e2701.
[INFO]	--> Setting version for github.com/pkg/errors to 645ef00459ed84a119197bfb8d8205042c6df63d.
[INFO]	--> Setting version for github.com/prometheus/client_golang to c5b7fccd204277076155f10851dad72b76a49317.
[INFO]	--> Setting version for github.com/prometheus/client_model to 99fa1f4be8e564e8a6b613da7fa6f46c9edafc6c.
[INFO]	--> Setting version for github.com/prometheus/common to e4aa40a9169a88835b849a6efb71e05dc04b88f0.
[INFO]	--> Setting version for github.com/prometheus/procfs to 54d17b57dd7d4a3aa092476596b3f8a933bde349.
[INFO]	--> Setting version for github.com/prometheus/prometheus to 0a74f98628a0463dddc90528220c94de5032d1a0.
[INFO]	--> Setting version for github.com/rcrowley/go-metrics to e2704e165165ec55d062f5919b4b29494e9fa790.
[INFO]	--> Setting version for github.com/rjeczalik/notify to d152f3ce359a5464dc41e84a8919fc67e55bbbf0.
[INFO]	--> Setting version for github.com/robertkrimen/otto to 15f95af6e78dcd2030d8195a138bd88d4f403546.
[INFO]	--> Setting version for github.com/rs/cors to 694cf2ad010fcf91ee35161f5bfdad8f42ed1b9a.
[INFO]	--> Setting version for github.com/spf13/afero to 787d034dfe70e44075ccc060d346146ef53270ad.
[INFO]	--> Setting version for github.com/spf13/cast to 8965335b8c7107321228e3e3702cab9832751bac.
[INFO]	--> Setting version for github.com/spf13/cobra to 1e58aa3361fd650121dceeedc399e7189c05674a.
[INFO]	--> Setting version for github.com/spf13/jwalterweatherman to 7c0cea34c8ece3fbeb2b27ab9b59511d360fb394.
[INFO]	--> Setting version for github.com/spf13/pflag to 3ebe029320b2676d667ae88da602a5f854788a8a.
[INFO]	--> Setting version for github.com/spf13/viper to 15738813a09db5c8e5b60a19d67d3f9bd38da3a4.
[INFO]	--> Setting version for github.com/syndtr/goleveldb to e2150783cd35f5b607daca48afd8c57ec54cc995.
[INFO]	--> Setting version for github.com/StackExchange/wmi to cdffdb33acae0e14efff2628f9bae377b597840e.
[INFO]	--> Setting version for github.com/tendermint/ed25519 to d8387025d2b9d158cf4efb07e7ebf814bcce2057.
[INFO]	--> Setting version for github.com/tendermint/go-amino to 2106ca61d91029c931fd54968c2bb02dc96b1412.
[INFO]	--> Setting version for github.com/tendermint/go-wire to fd33313baedb08fffafa3837994d3f02a6587baf.
[INFO]	--> Setting version for github.com/tendermint/iavl to 35f66e53d9b01e83b30de68b931f54b2477a94c9.
[INFO]	--> Setting version for github.com/tendermint/tendermint to dfa9a9a30a666132425b29454e90a472aa579a48.
[INFO]	--> Setting version for golang.org/x/crypto to c3a3ad6d03f7a915c0f7e194b7152974bb73d287.
[INFO]	--> Setting version for golang.org/x/sync to 1d60e4601c6fd243af51cc01ddf169918a5407ca.
[INFO]	--> Setting version for golang.org/x/text to f21a4dfb5e38f5895301dc265a8def02365cc3d0.
[INFO]	--> Setting version for golang.org/x/sys to d8e400bc7db4870d786864138af681469693d18c.
[INFO]	--> Setting version for google.golang.org/genproto to ff3583edef7de132f219f0efc00e097cabcc0ec0.
[INFO]	--> Setting version for github.com/pmezard/go-difflib to 792786c7400a136282c1664665ae0a8db921c6c2.
[INFO]	--> Setting version for github.com/stretchr/testify to f35b8ab0b5a2cef36673838d662e249dd9c94686.
[INFO]	--> Setting version for google.golang.org/grpc to 168a6198bcb0ef175f7dacec0b8691fc141dc9b8.
[INFO]	--> Setting version for gopkg.in/fatih/set.v0 to 2c768e3c5489976167bfc42b5c7c92ca783f4389.
[INFO]	--> Setting version for gopkg.in/karalabe/cookiejar.v2 to 8dcd6a7f4951f6ff3ee9cbb919a06d8925822e57.
[INFO]	--> Setting version for gopkg.in/natefinch/npipe.v2 to c1b8fa8bdccecb0b8db834ee0b92fdbcfa606dd6.
[INFO]	--> Setting version for gopkg.in/olebedev/go-duktape.v3 to abf0ba0be5d5d36b1f9266463cc320b9a5ab224e.
[INFO]	--> Setting version for gopkg.in/sourcemap.v1 to 6e83acea0053641eff084973fee085f0c193c61a.
[INFO]	--> Setting version for gopkg.in/urfave/cli.v1 to cfb38830724cc34fedffe9a2a29fb54fa9169cd1.
[INFO]	--> Setting version for gopkg.in/yaml.v2 to 5420a8b6744d3b0345ab293f6fcba19c978f1183.
[INFO]	--> Setting version for golang.org/x/net to 92b859f39abd2d91a854c9f9c4621b2f5054a92d.
[INFO]	Exporting resolved dependencies...
[INFO]	--> Exporting github.com/aristanetworks/goarista
[INFO]	--> Exporting github.com/beorn7/perks
[INFO]	--> Exporting github.com/bgentry/speakeasy
[INFO]	--> Exporting github.com/golang/snappy
[INFO]	--> Exporting github.com/davecgh/go-spew
[INFO]	--> Exporting github.com/BurntSushi/toml
[INFO]	--> Exporting github.com/ebuchman/fail-test
[INFO]	--> Exporting github.com/hashicorp/golang-lru
[INFO]	--> Exporting github.com/elastic/gosigar
[INFO]	--> Exporting github.com/ethereum/go-ethereum
[INFO]	--> Exporting github.com/huin/goupnp
[INFO]	--> Exporting github.com/fatih/color
[INFO]	--> Exporting github.com/fjl/memsize
[INFO]	--> Exporting github.com/fsnotify/fsnotify
[INFO]	--> Exporting github.com/go-kit/kit
[INFO]	--> Exporting github.com/go-logfmt/logfmt
[INFO]	--> Exporting github.com/go-ole/go-ole
[INFO]	--> Exporting github.com/go-stack/stack
[INFO]	--> Exporting github.com/gogo/protobuf
[INFO]	--> Exporting github.com/golang/protobuf
[INFO]	--> Exporting github.com/btcsuite/btcd
[INFO]	--> Exporting github.com/edsrzf/mmap-go
[INFO]	--> Exporting github.com/hashicorp/hcl
[INFO]	--> Exporting github.com/gorilla/websocket
[INFO]	--> Exporting github.com/inconshreveable/mousetrap
[INFO]	--> Exporting github.com/influxdata/influxdb
[INFO]	--> Exporting github.com/jackpal/go-nat-pmp
[INFO]	--> Exporting github.com/jmhodges/levigo
[INFO]	--> Exporting github.com/karalabe/hid
[INFO]	--> Exporting github.com/kr/logfmt
[INFO]	--> Exporting github.com/magiconair/properties
[INFO]	--> Exporting github.com/mattn/go-colorable
[INFO]	--> Exporting github.com/mattn/go-isatty
[INFO]	--> Exporting github.com/mattn/go-runewidth
[INFO]	--> Exporting github.com/mattn/go-sqlite3
[INFO]	--> Exporting github.com/matttproud/golang_protobuf_extensions
[INFO]	--> Exporting github.com/mitchellh/mapstructure
[INFO]	--> Exporting github.com/pborman/uuid
[INFO]	--> Exporting github.com/pelletier/go-toml
[INFO]	--> Exporting github.com/peterh/liner
[INFO]	--> Exporting github.com/pkg/errors
[INFO]	--> Exporting github.com/prometheus/client_golang
[INFO]	--> Exporting github.com/prometheus/client_model
[INFO]	--> Exporting github.com/prometheus/common
[INFO]	--> Exporting github.com/prometheus/procfs
[INFO]	--> Exporting github.com/prometheus/prometheus
[INFO]	--> Exporting github.com/rcrowley/go-metrics
[INFO]	--> Exporting github.com/rjeczalik/notify
[INFO]	--> Exporting github.com/robertkrimen/otto
[INFO]	--> Exporting github.com/rs/cors
[INFO]	--> Exporting github.com/spf13/afero
[INFO]	--> Exporting github.com/spf13/cobra
[INFO]	--> Exporting github.com/spf13/cast
[INFO]	--> Exporting github.com/spf13/jwalterweatherman
[INFO]	--> Exporting github.com/spf13/pflag
[INFO]	--> Exporting github.com/spf13/viper
[INFO]	--> Exporting github.com/StackExchange/wmi
[INFO]	--> Exporting github.com/syndtr/goleveldb
[INFO]	--> Exporting github.com/tendermint/ed25519
[INFO]	--> Exporting github.com/tendermint/go-amino
[INFO]	--> Exporting github.com/tendermint/go-wire
[INFO]	--> Exporting github.com/tendermint/iavl
[INFO]	--> Exporting github.com/tendermint/tendermint
[INFO]	--> Exporting golang.org/x/net
[INFO]	--> Exporting golang.org/x/sync
[INFO]	--> Exporting google.golang.org/genproto
[INFO]	--> Exporting github.com/pmezard/go-difflib
[INFO]	--> Exporting google.golang.org/grpc
[INFO]	--> Exporting golang.org/x/text
[INFO]	--> Exporting github.com/stretchr/testify
[INFO]	--> Exporting golang.org/x/sys
[INFO]	--> Exporting gopkg.in/fatih/set.v0
[INFO]	--> Exporting gopkg.in/karalabe/cookiejar.v2
[INFO]	--> Exporting gopkg.in/natefinch/npipe.v2
[INFO]	--> Exporting gopkg.in/sourcemap.v1
[INFO]	--> Exporting gopkg.in/olebedev/go-duktape.v3
[INFO]	--> Exporting gopkg.in/yaml.v2
[INFO]	--> Exporting gopkg.in/urfave/cli.v1
[INFO]	--> Exporting golang.org/x/crypto
[INFO]	Replacing existing vendor dependencies

--> Installing the Travis TestNet

CGO_LDFLAGS="-L/home/huobi/.travis/eni/lib -Wl,-rpath,/home/huobi/.travis/eni/lib" CGO_LDFLAGS_ALLOW=""-I.*"" go install ./cmd/travis
# github.com/CyberMiles/travis/vendor/github.com/ethereum/go-ethereum/core/vm/eni
In file included from vendor/github.com/ethereum/go-ethereum/core/vm/eni/eni.go:9:0:
vendor/github.com/ethereum/go-ethereum/core/vm/eni/fork_call.h: In function ‘fork_call’:
vendor/github.com/ethereum/go-ethereum/core/vm/eni/fork_call.h:57:26: warning: format ‘%lld’ expects argument of type ‘long long int’, but argument 3 has type ‘int64_t {aka long int}’ [-Wformat=]
             sprintf(str, "%lld", *gas);
                          ^
vendor/github.com/ethereum/go-ethereum/core/vm/eni/fork_call.h:89:17: warning: implicit declaration of function ‘wait’ [-Wimplicit-function-declaration]
                 wait(status);
                 ^
vendor/github.com/ethereum/go-ethereum/core/vm/eni/fork_call.h:93:21: warning: implicit declaration of function ‘waitpid’ [-Wimplicit-function-declaration]
             if(0 != waitpid(pid, status, WNOHANG)) break;
                     ^
vendor/github.com/ethereum/go-ethereum/core/vm/eni/fork_call.h:108:32: warning: format ‘%lld’ expects argument of type ‘long long int *’, but argument 3 has type ‘int64_t * {aka long int *}’ [-Wformat=]
             sscanf((char*)ret, "%lld\n", gas);
                                ^
vendor/github.com/ethereum/go-ethereum/core/vm/eni/fork_call.h:58:13: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
             write(pfd[1], str, strlen(str)+1); // (with \0 would end read())
             ^
vendor/github.com/ethereum/go-ethereum/core/vm/eni/fork_call.h:62:13: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
             write(pfd[1], retText, strlen(retText)+1); // (with \0 would end read())
             ^
    #  github.com/CyberMiles/travis/cmd/travis
github.com/CyberMiles/travis/vendor/github.com/ethereum/go-ethereum/crypto/bn256/cloudflare.gfpMul: relocation target runtime.support_bmi2 not defined
Makefile:16: recipe for target 'install' failed
make: *** [install] Error 2

**Comment by Night-mk** [comment]
I got the same question, my configuration is same to you, do you solve it now?

**Comment by tpmccallum** [comment]
Let me know if this Gist helps.
https://gist.github.com/tpmccallum/64a0d69f456118ef0b44a68937776c10
