### ISSUE TITLE
关于VM性能问题的测试

### ISSUE THREAD

**Issue by ives-x** [CyberMiles/travis#14]
我按照说明运行了一个Travis在同一台GoogleCLoud的VPS上也运行了Ethereum的节点, 将https://gist.github.com/juntao/0249a9bf7bd332ad01959973398f6a33 这个页面的solidity合约部署到了两个网络进行测试, 发现情况并不理想, 以下是测试结果 , 
add(2000000) 循环20次 测试
eth 16.642 s
cmt 17.073 s

mul(1000000) 循环20次 测试
eth 49.051 s
cmt 104.479 s

sort(6000) 循环20次 测试
eth 79.591 s
cmt 104.842 s

这和官方宣传的不太一致, 是我测试的方法不对吗

**Comment by juntao** [comment]
CVM 上面是用 Lity + libENI 实现的，不再用 plain solidity.

LibENI code 也在网页上有。

Cheers
Michael


-----------------------------
Michael Yuan, PhD
http://www.michaelyuan.com
________________________________

**Comment by ives-x** [comment]
我部署了这个合约 https://gist.github.com/juntao/77022bf5c27550d7175897db69f8a8a2 , 但是在调用的时候发生了这个错误, 应该怎么解决呢
![image](https://user-images.githubusercontent.com/25735971/46062981-ffc61d00-c19d-11e8-903e-4d85834a671a.png)

**Comment by Night-mk** [comment]
how can I use the cpp file in this link: https://gist.github.com/juntao/77022bf5c27550d7175897db69f8a8a2
just compile it? but how to link with .sol file?
is there any doc for the VM test?
