### ISSUE TITLE
Error in Setting up Travis

### ISSUE THREAD

**Issue by srishti-khandelwal** [CyberMiles/travis#15]
I used docker to connect to the Cybermiles Testnet : 
After running this command: `docker run --name travis -v $HOME/.travis:/travis -p 26657:26657 -p 8545:8545 -t cybermiles/travis node start --home /travis`

I get the following response:
INFO [10-12|06:08:21.594] Maximum peer count                       ETH=25 LES=0 total=25
INFO [10-12|06:08:21.717] Starting peer-to-peer node               instance=vm/v1.8.12-stable/linux-amd64/go1.10.3
INFO [10-12|06:08:21.717] Allocated cache and file handles         database=/travis/vm/chaindata cache=768 handles=1024
INFO [10-12|06:08:22.037] Initialised chain configuration          config="{ChainID: 19 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: <nil> EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: <nil> Engine: unknown}"
WARN [10-12|06:08:22.037] Ethash used in fake mode 
INFO [10-12|06:08:22.038] Initialising Ethereum protocol           versions="[63 62]" network=19
INFO [10-12|06:08:22.043] Loaded most recent local header          number=475 hash=2bb05b…d7876f td=69992712
INFO [10-12|06:08:22.043] Loaded most recent local full block      number=475 hash=2bb05b…d7876f td=69992712
INFO [10-12|06:08:22.043] Loaded most recent local fast block      number=475 hash=2bb05b…d7876f td=69992712
INFO [10-12|06:08:22.044] Loaded local transaction journal         transactions=0 dropped=0
INFO [10-12|06:08:22.044] Regenerated local transaction journal    transactions=0 accounts=0
WARN [10-12|06:08:22.044] Blockchain not empty, fast sync disabled 
INFO [10-12|06:08:22.045] Starting P2P networking 
INFO [10-12|06:08:22.045] RLPx listener up                         self="enode://8868f8ac7cc04f7d5e6778c80ba81a64d107965a1e03294aadeb2e0df5c7666c836020f69d2c4ccb6e7cac0a05225edc3e9f30fb43596637654bd37182d96417@[::]:30303?discport=0"
INFO [10-12|06:08:22.086] IPC endpoint opened                      url=/travis/geth.ipc
INFO [10-12|06:08:22.088] HTTP endpoint opened                     url=http://0.0.0.0:8545 cors= vhosts=localhost
E[10-12|06:08:25.327] Dialing failed                               module=p2p addr=bc520723c1f1b658f2c8ad32bc2d5aec9c3792c9@157.119.234.8:26656 err="Error{dial tcp 157.119.234.8:26656: connect: no route to host}" attempts=0
E[10-12|06:08:25.327] Dialing failed                               module=p2p addr=31d2efc0b1eaa10e98267055756cbbfc8396b7f4@157.119.234.8:26656 err="Error{dial tcp 157.119.234.8:26656: connect: no route to host}" attempts=0
E[10-12|06:08:25.327] Dialing failed                               module=p2p addr=b8ea21c520f12edab79da2a5a017b29d980e74eb@212.71.238.33:26656 err="Error{dial tcp 212.71.238.33:26656: connect: connection refused}" attempts=0
E[10-12|06:08:25.346] Dialing failed                               module=p2p addr=f3485abd4ad30fb2242ac0ed0a65de3ee9466ef6@157.119.234.8:26656 err="Error{dial tcp 157.119.234.8:26656: connect: no route to host}" attempts=0
E[10-12|06:08:25.532] Dialing failed                               module=p2p addr=4ed833daf70c2a0f438a5a5ef50894b462af1544@149.28.172.124:26656 err="Error{dial tcp 149.28.172.124:26656: connect: connection refused}" attempts=0
E[10-12|06:08:28.141] Dialing failed                               module=p2p addr=9a2c576cbae93065318ffab37bce1b7a32d57dff@18.224.1.174:26656 err="Error{dial tcp 18.224.1.174:26656: i/o timeout}" attempts=0
E[10-12|06:08:28.141] Dialing failed                               module=p2p addr=dc9270efc18c6d7c106f89f6d3b2600b5a86e793@13.59.104.238:26656 err="Error{dial tcp 13.59.104.238:26656: i/o timeout}" attempts=0
E[10-12|06:08:28.141] Dialing failed                               module=p2p addr=6663fe27abda99dd097d0b02a5b54790eb7602af@18.223.152.127:26656 err="Error{dial tcp 18.223.152.127:26656: i/o timeout}" attempts=0
E[10-12|06:08:28.142] Dialing failed                               module=p2p addr=0a21528dca29be996c2246d6463402e66427ec6e@52.15.41.127:26656 err="Error{dial tcp 52.15.41.127:26656: i/o timeout}" attempts=0
E[10-12|06:08:29.500] Error dialing peer                           module=p2p err="Error{dial tcp 13.59.104.238:26656: i/o timeout}"
E[10-12|06:08:30.609] Error dialing peer                           module=p2p err="Error{dial tcp 18.223.152.127:26656: i/o timeout}"
E[10-12|06:08:55.303] Dialing failed                               module=p2p addr=b8ea21c520f12edab79da2a5a017b29d980e74eb@212.71.238.33:26656 err="Error{dial tcp 212.71.238.33:26656: connect: connection refused}" attempts=1
E[10-12|06:08:55.303] Dialing failed                               module=p2p addr=bc520723c1f1b658f2c8ad32bc2d5aec9c3792c9@157.119.234.8:26656 err="Error{dial tcp 157.119.234.8:26656: connect: no route to host}" attempts=1
E[10-12|06:08:55.342] Dialing failed                               module=p2p addr=f3485abd4ad30fb2242ac0ed0a65de3ee9466ef6@157.119.234.8:26656 err="Error{dial tcp 157.119.234.8:26656: connect: no route to host}" attempts=1
E[10-12|06:08:55.342] Dialing failed                               module=p2p addr=7ce9a8b53a4b679be5a048a1cb989a3e090ad10f@157.119.234.8:26656 err="Error{dial tcp 157.119.234.8:26656: connect: no route to host}" attempts=1
E[10-12|06:08:55.385] Dialing failed                               module=p2p addr=4ed833daf70c2a0f438a5a5ef50894b462af1544@149.28.172.124:26656 err="Error{dial tcp 149.28.172.124:26656: connect: connection refused}" attempts=1
E[10-12|06:08:58.141] Dialing failed                               module=p2p addr=0a21528dca29be996c2246d6463402e66427ec6e@52.15.41.127:26656 err="Error{dial tcp 52.15.41.127:26656: i/o timeout}" attempts=1
E[10-12|06:08:58.141] Dialing failed                               module=p2p addr=9a2c576cbae93065318ffab37bce1b7a32d57dff@18.224.1.174:26656 err="Error{dial tcp 18.224.1.174:26656: i/o timeout}" attempts=1
E[10-12|06:08:58.141] Dialing failed                               module=p2p addr=dc9270efc18c6d7c106f89f6d3b2600b5a86e793@13.59.104.238:26656 err="Error{dial tcp 13.59.104.238:26656: i/o timeout}" attempts=1
E[10-12|06:08:58.142] Dialing failed                               module=p2p addr=6663fe27abda99dd097d0b02a5b54790eb7602af@18.223.152.127:26656 err="Error{dial tcp 18.223.152.127:26656: i/o timeout}" attempts=1
E[10-12|06:09:25.249] Dialing failed                               module=p2p addr=7ce9a8b53a4b679be5a048a1cb989a3e090ad10f@157.119.234.8:26656 err="Error{dial tcp 157.119.234.8:26656: connect: no route to host}" attempts=2
E[10-12|06:09:25.283] Dialing failed                               module=p2p addr=b8ea21c520f12edab79da2a5a017b29d980e74eb@212.71.238.33:26656 err="Error{dial tcp 212.71.238.33:26656: connect: connection refused}" attempts=2
E[10-12|06:09:25.346] Dialing failed                               module=p2p addr=f3485abd4ad30fb2242ac0ed0a65de3ee9466ef6@157.119.234.8:26656 err="Error{dial tcp 157.119.234.8:26656: connect: no route to host}" attempts=2
E[10-12|06:09:28.141] Dialing failed                               module=p2p addr=0a21528dca29be996c2246d6463402e66427ec6e@52.15.41.127:26656 err="Error{dial tcp 52.15.41.127:26656: i/o timeout}" attempts=2
E[10-12|06:09:28.141] Dialing failed                               module=p2p addr=9a2c576cbae93065318ffab37bce1b7a32d57dff@18.224.1.174:26656 err="Error{dial tcp 18.224.1.174:26656: i/o timeout}" attempts=2
E[10-12|06:09:28.141] Dialing failed                               module=p2p addr=6663fe27abda99dd097d0b02a5b54790eb7602af@18.223.152.127:26656 err="Error{dial tcp 18.223.152.127:26656: i/o timeout}" attempts=2
E[10-12|06:09:55.315] Dialing failed                               module=p2p addr=b8ea21c520f12edab79da2a5a017b29d980e74eb@212.71.238.33:26656 err="Error{dial tcp 212.71.238.33:26656: connect: connection refused}" attempts=3
E[10-12|06:09:55.343] Dialing failed                               module=p2p addr=bc520723c1f1b658f2c8ad32bc2d5aec9c3792c9@157.119.234.8:26656 err="Error{dial tcp 157.119.234.8:26656: connect: no route to host}" attempts=3
E[10-12|06:09:55.520] Dialing failed                               module=p2p addr=4ed833daf70c2a0f438a5a5ef50894b462af1544@149.28.172.124:26656 err="Error{dial tcp 149.28.172.124:26656: connect: connection refused}" attempts=2
E[10-12|06:09:58.141] Dialing failed                               module=p2p addr=9a2c576cbae93065318ffab37bce1b7a32d57dff@18.224.1.174:26656 err="Error{dial tcp 18.224.1.174:26656: i/o timeout}" attempts=3
E[10-12|06:09:58.141] Dialing failed                               module=p2p addr=0a21528dca29be996c2246d6463402e66427ec6e@52.15.41.127:26656 err="Error{dial tcp 52.15.41.127:26656: i/o timeout}" attempts=3
E[10-12|06:09:58.141] Dialing failed                               module=p2p addr=6663fe27abda99dd097d0b02a5b54790eb7602af@18.223.152.127:26656 err="Error{dial tcp 18.223.152.127:26656: i/o timeout}" attempts=3
E[10-12|06:10:25.314] Dialing failed                               module=p2p addr=b8ea21c520f12edab79da2a5a017b29d980e74eb@212.71.238.33:26656 err="Error{dial tcp 212.71.238.33:26656: connect: connection refused}" attempts=4
E[10-12|06:10:25.314] Dialing failed                               module=p2p addr=7ce9a8b53a4b679be5a048a1cb989a3e090ad10f@157.119.234.8:26656 err="Error{dial tcp 157.119.234.8:26656: connect: no route to host}" attempts=4
E[10-12|06:10:25.314] Dialing failed                               module=p2p addr=bc520723c1f1b658f2c8ad32bc2d5aec9c3792c9@157.119.234.8:26656 err="Error{dial tcp 157.119.234.8:26656: connect: no route to host}" attempts=4
E[10-12|06:10:25.347] Dialing failed                               module=p2p addr=31d2efc0b1eaa10e98267055756cbbfc8396b7f4@157.119.234.8:26656 err="Error{dial tcp 157.119.234.8:26656: connect: no route to host}" attempts=4
E[10-12|06:10:25.398] Dialing failed                               module=p2p addr=4ed833daf70c2a0f438a5a5ef50894b462af1544@149.28.172.124:26656 err="Error{dial tcp 149.28.172.124:26656: connect: connection refused}" attempts=3
E[10-12|06:10:28.146] Dialing failed                               module=p2p addr=9a2c576cbae93065318ffab37bce1b7a32d57dff@18.224.1.174:26656 err="Error{dial tcp 18.224.1.174:26656: i/o timeout}" attempts=4
E[10-12|06:10:28.146] Dialing failed                               module=p2p addr=dc9270efc18c6d7c106f89f6d3b2600b5a86e793@13.59.104.238:26656 err="Error{dial tcp 13.59.104.238:26656: i/o timeout}" attempts=2
E[10-12|06:10:28.147] Dialing failed                               module=p2p addr=6663fe27abda99dd097d0b02a5b54790eb7602af@18.223.152.127:26656 err="Error{dial tcp 18.223.152.127:26656: i/o timeout}" attempts=4
E[10-12|06:10:28.147] Dialing failed                               module=p2p addr=0a21528dca29be996c2246d6463402e66427ec6e@52.15.41.127:26656 err="Error{dial tcp 52.15.41.127:26656: i/o timeout}" attempts=4
E[10-12|06:10:58.141] Dialing failed                               module=p2p addr=dc9270efc18c6d7c106f89f6d3b2600b5a86e793@13.59.104.238:26656 err="Error{dial tcp 13.59.104.238:26656: i/o timeout}" attempts=3
E[10-12|06:11:25.278] Dialing failed                               module=p2p addr=7ce9a8b53a4b679be5a048a1cb989a3e090ad10f@157.119.234.8:26656 err="Error{dial tcp 157.119.234.8:26656: connect: no route to host}" attempts=5
E[10-12|06:11:25.278] Dialing failed                               module=p2p addr=b8ea21c520f12edab79da2a5a017b29d980e74eb@212.71.238.33:26656 err="Error{dial tcp 212.71.238.33:26656: connect: connection refused}" attempts=5
E[10-12|06:11:25.344] Dialing failed                               module=p2p addr=31d2efc0b1eaa10e98267055756cbbfc8396b7f4@157.119.234.8:26656 err="Error{dial tcp 157.119.234.8:26656: connect: no route to host}" attempts=5
E[10-12|06:11:25.386] Dialing failed                               module=p2p addr=4ed833daf70c2a0f438a5a5ef50894b462af1544@149.28.172.124:26656 err="Error{dial tcp 149.28.172.124:26656: connect: connection refused}" attempts=4
E[10-12|06:11:28.142] Dialing failed                               module=p2p addr=9a2c576cbae93065318ffab37bce1b7a32d57dff@18.224.1.174:26656 err="Error{dial tcp 18.224.1.174:26656: i/o timeout}" attempts=5
E[10-12|06:11:28.142] Dialing failed                               module=p2p addr=dc9270efc18c6d7c106f89f6d3b2600b5a86e793@13.59.104.238:26656 err="Error{dial tcp 13.59.104.238:26656: i/o timeout}" attempts=4
E[10-12|06:11:28.142] Dialing failed                               module=p2p addr=0a21528dca29be996c2246d6463402e66427ec6e@52.15.41.127:26656 err="Error{dial tcp 52.15.41.127:26656: i/o timeout}" attempts=5
E[10-12|06:11:38.796] Failed to reconnect to peer. Beginning exponential backoff module=p2p addr=dc9270efc18c6d7c106f89f6d3b2600b5a86e793@13.59.104.238:26656 elapsed=3m9.295928938s
E[10-12|06:11:39.994] Failed to reconnect to peer. Beginning exponential backoff module=p2p addr=6663fe27abda99dd097d0b02a5b54790eb7602af@18.223.152.127:26656 elapsed=3m9.385088326s
E[10-12|06:11:58.141] Dialing failed                               module=p2p addr=6663fe27abda99dd097d0b02a5b54790eb7602af@18.223.152.127:26656 err="Error{dial tcp 18.223.152.127:26656: i/o timeout}" attempts=5
E[10-12|06:12:25.638] Dialing failed                               module=p2p addr=4ed833daf70c2a0f438a5a5ef50894b462af1544@149.28.172.124:26656 err="Error{dial tcp 149.28.172.124:26656: connect: connection refused}" attempts=5
E[10-12|06:12:28.286] Dialing failed                               module=p2p addr=dc9270efc18c6d7c106f89f6d3b2600b5a86e793@13.59.104.238:26656 err="Error{dial tcp 13.59.104.238:26656: i/o timeout}" attempts=5
E[10-12|06:12:55.346] Dialing failed                               module=p2p addr=7ce9a8b53a4b679be5a048a1cb989a3e090ad10f@157.119.234.8:26656 err="Error{dial tcp 157.119.234.8:26656: connect: no route to host}" attempts=6
E[10-12|06:12:55.346] Dialing failed                               module=p2p addr=f3485abd4ad30fb2242ac0ed0a65de3ee9466ef6@157.119.234.8:26656 err="Error{dial tcp 157.119.234.8:26656: connect: no route to host}" attempts=6
E[10-12|06:12:55.349] Dialing failed                               module=p2p addr=b8ea21c520f12edab79da2a5a017b29d980e74eb@212.71.238.33:26656 err="Error{dial tcp 212.71.238.33:26656: connect: connection refused}" attempts=6
E[10-12|06:12:58.141] Dialing failed                               module=p2p addr=9a2c576cbae93065318ffab37bce1b7a32d57dff@18.224.1.174:26656 err="Error{dial tcp 18.224.1.174:26656: i/o timeout}" attempts=6
E[10-12|06:12:58.141] Dialing failed                               module=p2p addr=0a21528dca29be996c2246d6463402e66427ec6e@52.15.41.127:26656 err="Error{dial tcp 52.15.41.127:26656: i/o timeout}" attempts=6
E[10-12|06:13:28.141] Dialing failed                               module=p2p addr=6663fe27abda99dd097d0b02a5b54790eb7602af@18.223.152.127:26656 err="Error{dial tcp 18.223.152.127:26656: i/o timeout}" attempts=6
E[10-12|06:13:58.141] Dialing failed                               module=p2p addr=dc9270efc18c6d7c106f89f6d3b2600b5a86e793@13.59.104.238:26656 err="Error{dial tcp 13.59.104.238:26656: i/o timeout}" attempts=6
E[10-12|06:15:25.451] Dialing failed                               module=p2p addr=bc520723c1f1b658f2c8ad32bc2d5aec9c3792c9@157.119.234.8:26656 err="Error{dial tcp 157.119.234.8:26656: connect: no route to host}" attempts=7
E[10-12|06:15:25.451] Dialing failed                               module=p2p addr=b8ea21c520f12edab79da2a5a017b29d980e74eb@212.71.238.33:26656 err="Error{dial tcp 212.71.238.33:26656: connect: connection refused}" attempts=7
E[10-12|06:15:25.597] Dialing failed                               module=p2p addr=4ed833daf70c2a0f438a5a5ef50894b462af1544@149.28.172.124:26656 err="Error{dial tcp 149.28.172.124:26656: connect: connection refused}" attempts=6
E[10-12|06:15:28.142] Dialing failed                               module=p2p addr=9a2c576cbae93065318ffab37bce1b7a32d57dff@18.224.1.174:26656 err="Error{dial tcp 18.224.1.174:26656: i/o timeout}" attempts=7
E[10-12|06:15:28.142] Dialing failed                               module=p2p addr=0a21528dca29be996c2246d6463402e66427ec6e@52.15.41.127:26656 err="Error{dial tcp 52.15.41.127:26656: i/o timeout}" attempts=7
E[10-12|06:15:58.141] Dialing failed                               module=p2p addr=6663fe27abda99dd097d0b02a5b54790eb7602af@18.223.152.127:26656 err="Error{dial tcp 18.223.152.127:26656: i/o timeout}" attempts=7
E[10-12|06:16:28.141] Dialing failed                               module=p2p addr=dc9270efc18c6d7c106f89f6d3b2600b5a86e793@13.59.104.238:26656 err="Error{dial tcp 13.59.104.238:26656: i/o timeout}" attempts=7

Thanks for any help :)

**Comment by tpmccallum** [comment]
I just re-installed using Docker on Ubuntu 16.04 and it worked for me.

Is this an older install that you are starting up again today?
Just curious about the connectivity of your machine i.e. can you ping other machines on the web? (what do you get if you try the following command)
Also, what operating system (and version) are you using?
```
ping 1.1.1.1
```
Should get a response like this
```
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
64 bytes from 1.1.1.1: icmp_seq=1 ttl=51 time=0.780 ms
64 bytes from 1.1.1.1: icmp_seq=2 ttl=51 time=0.775 ms
64 bytes from 1.1.1.1: icmp_seq=3 ttl=51 time=0.806 ms
64 bytes from 1.1.1.1: icmp_seq=4 ttl=51 time=0.789 ms
^C
--- 1.1.1.1 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 2997ms
```
You will notice that my install fetched a fresh pull of everything; it may be necessary to do a completely fresh install if you are out of ideas.

```
Last login: Fri Oct 12 07:39:06 2018 from xxx.xx.xxx.xx
ubuntu@ip-172-31-14-62:~$ docker run --name travis -v $HOME/.travis:/travis -p 26657:26657 -p 8545:8545 -t cybermiles/travis node start --home /travis
Unable to find image 'cybermiles/travis:latest' locally
latest: Pulling from cybermiles/travis
3b37166ec614: Pull complete 
504facff238f: Pull complete 
ebbcacd28e10: Pull complete 
c7fb3351ecad: Pull complete 
2e3debadcbf7: Pull complete 
e04272ec6040: Pull complete 
0a71ebb09808: Pull complete 
4945f8e64582: Pull complete 
28654a81d1b3: Pull complete 
Digest: sha256:b7dd4a873fabe62dc11c9152b1aadc3963f98ed411ef8dbf6573d41f1f07c7d6
Status: Downloaded newer image for cybermiles/travis:latest
INFO [10-12|07:42:37.557] Maximum peer count                       ETH=25 LES=0 total=25
INFO [10-12|07:42:37.557] Starting peer-to-peer node               instance=vm/v1.8.12-stable/linux-amd64/go1.10.3
INFO [10-12|07:42:37.557] Allocated cache and file handles         database=/travis/vm/chaindata cache=768 handles=1024
INFO [10-12|07:42:37.569] Initialised chain configuration          config="{ChainID: 19 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: <nil> EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: <nil> Engine: unknown}"
WARN [10-12|07:42:37.569] Ethash used in fake mode 
INFO [10-12|07:42:37.569] Initialising Ethereum protocol           versions="[63 62]" network=19
INFO [10-12|07:42:37.570] Loaded most recent local header          number=0 hash=131599…ff6994 td=64
INFO [10-12|07:42:37.570] Loaded most recent local full block      number=0 hash=131599…ff6994 td=64
INFO [10-12|07:42:37.570] Loaded most recent local fast block      number=0 hash=131599…ff6994 td=64
INFO [10-12|07:42:37.570] Regenerated local transaction journal    transactions=0 accounts=0
INFO [10-12|07:42:37.571] Starting P2P networking 
INFO [10-12|07:42:37.571] RLPx listener up                         self="enode://d9504c162444933bd32bfd349d0abfa7d35b3e61ceb3bd2883435590f7eb9f1234bf1513f2bc84ef1e5ae5698287e8297d615174db060a34ecacfa8f513923e6@[::]:30303?discport=0"
INFO [10-12|07:42:37.573] IPC endpoint opened                      url=/travis/geth.ipc
INFO [10-12|07:42:37.574] HTTP endpoint opened                     url=http://0.0.0.0:8545 cors= vhosts=localhost
I[10-12|07:42:43.025] Executed block                               module=state height=1 validTxs=1 invalidTxs=0
I[10-12|07:42:43.025] Updates to validators                        module=state updates="[{\"address\":\"\",\"pub_key\":\"nPojdfSyBzzF9ZXucS3lknbP7CDIcwoZUYqPRqfmnoU=\",\"power\":4410},{\"address\":\"\",\"pub_key\":\"H3Lt1MgnypS7AxjHIPhUm6ULmY8ZYkmOOzAC2BYKGRg=\",\"power\":4410},{\"address\":\"\",\"pub_key\":\"t5AbfYr4Ewy6vnjHzVZU3Y+aPUEQWL4w+21c1WQz7bs=\",\"power\":4410},{\"address\":\"\",\"pub_key\":\"/ZtWfmxoAm41dXgvA7u71Cgvjkj0jyn4YLZqGno9X0g=\",\"power\":4410}]"
INFO [10-12|07:42:43.028] Imported new chain segment               blocks=1 txs=1 mgas=1.483 elapsed=656.615µs mgasps=2258.296 number=1 hash=9c992f…e1883c cache=7.65kB
I[10-12|07:42:43.034] Committed state                              module=state height=1 txs=1 appHash=D458F434D00C74D1E80A9599B7A4F4FBEF440A7D
I[10-12|07:42:43.050] Executed block                               module=state height=2 validTxs=0 invalidTxs=0

```
 Let me know if you need me to paste in the commands that I ran to get the testnet installed and syncing on Ubuntu 16.04.

Kind regards
Tim

**Comment by srishti-khandelwal** [comment]
on executing command: ping 1.1.1.1

response::::::::

PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
64 bytes from 1.1.1.1: icmp_seq=1 ttl=250 time=7.24 ms
64 bytes from 1.1.1.1: icmp_seq=2 ttl=250 time=20.4 ms
64 bytes from 1.1.1.1: icmp_seq=3 ttl=250 time=7.29 ms
64 bytes from 1.1.1.1: icmp_seq=4 ttl=250 time=14.0 ms
64 bytes from 1.1.1.1: icmp_seq=5 ttl=250 time=7.39 ms
64 bytes from 1.1.1.1: icmp_seq=6 ttl=250 time=7.37 ms
64 bytes from 1.1.1.1: icmp_seq=7 ttl=250 time=18.1 ms
64 bytes from 1.1.1.1: icmp_seq=8 ttl=250 time=9.32 ms
64 bytes from 1.1.1.1: icmp_seq=9 ttl=250 time=7.37 ms
64 bytes from 1.1.1.1: icmp_seq=10 ttl=250 time=7.35 ms
64 bytes from 1.1.1.1: icmp_seq=11 ttl=250 time=11.2 ms
64 bytes from 1.1.1.1: icmp_seq=12 ttl=250 time=19.7 ms
64 bytes from 1.1.1.1: icmp_seq=13 ttl=250 time=6.92 ms
64 bytes from 1.1.1.1: icmp_seq=14 ttl=250 time=10.1 ms
64 bytes from 1.1.1.1: icmp_seq=15 ttl=250 time=7.00 ms
64 bytes from 1.1.1.1: icmp_seq=16 ttl=250 time=7.23 ms
64 bytes from 1.1.1.1: icmp_seq=17 ttl=250 time=6.97 ms
64 bytes from 1.1.1.1: icmp_seq=18 ttl=250 time=7.13 ms
64 bytes from 1.1.1.1: icmp_seq=19 ttl=250 time=8.62 ms
64 bytes from 1.1.1.1: icmp_seq=20 ttl=250 time=8.32 ms
64 bytes from 1.1.1.1: icmp_seq=21 ttl=250 time=7.27 ms
64 bytes from 1.1.1.1: icmp_seq=22 ttl=250 time=7.33 ms
64 bytes from 1.1.1.1: icmp_seq=24 ttl=250 time=9.49 ms
64 bytes from 1.1.1.1: icmp_seq=25 ttl=250 time=15.7 ms
64 bytes from 1.1.1.1: icmp_seq=26 ttl=250 time=9.45 ms
64 bytes from 1.1.1.1: icmp_seq=27 ttl=250 time=8.53 ms
64 bytes from 1.1.1.1: icmp_seq=28 ttl=250 time=10.0 ms
64 bytes from 1.1.1.1: icmp_seq=29 ttl=250 time=8.66 ms
64 bytes from 1.1.1.1: icmp_seq=30 ttl=250 time=23.7 ms
64 bytes from 1.1.1.1: icmp_seq=31 ttl=250 time=6.74 ms
64 bytes from 1.1.1.1: icmp_seq=32 ttl=250 time=7.45 ms
64 bytes from 1.1.1.1: icmp_seq=33 ttl=250 time=14.6 ms
64 bytes from 1.1.1.1: icmp_seq=34 ttl=250 time=8.56 ms
64 bytes from 1.1.1.1: icmp_seq=35 ttl=250 time=27.8 ms
64 bytes from 1.1.1.1: icmp_seq=36 ttl=250 time=157 ms
64 bytes from 1.1.1.1: icmp_seq=37 ttl=250 time=9.85 ms
64 bytes from 1.1.1.1: icmp_seq=38 ttl=250 time=7.71 ms
^C
--- 1.1.1.1 ping statistics ---
38 packets transmitted, 37 received, 2% packet loss, time 37077ms
rtt min/avg/max/mdev = 6.746/14.589/157.259/24.324 ms


And yes I used an older install, starting it again today. Is that a problem ? should I repeat the whole process again ?

Additional Information: I am working on Ubuntu 16.04

**Comment by tpmccallum** [comment]
If you could do a fresh install that would be brilliant. That way you will be running all of the latest code and config. 
The following two sites should give you all of the commands you need for a fresh install on a fresh instance

https://docs.docker.com/install/linux/docker-ce/ubuntu/
https://travis.readthedocs.io/en/latest/connect-testnet.html#docker

Please let us know if you need any help and make sure that you provide some more details about OS etc if you do reach out. All the best  👍

Kind regards
Tim

**Comment by srishti-khandelwal** [comment]
I did a fresh start( except pulling the docker image) i.e. deleted the .travis directory and then followed the steps as specified, i still get the following response:::::
docker run --name travis -v $HOME/.travis:/travis -p 26657:26657 -p 8545:8545 -t cybermiles/travis node start --home /travisINFO [10-12|09:39:42.877] Maximum peer count                       ETH=25 LES=0 total=25
INFO [10-12|09:39:42.908] Starting peer-to-peer node               instance=vm/v1.8.12-stable/linux-amd64/go1.10.3
INFO [10-12|09:39:42.908] Allocated cache and file handles         database=/travis/vm/chaindata cache=768 handles=1024
INFO [10-12|09:39:43.078] Initialised chain configuration          config="{ChainID: 19 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: <nil> EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: <nil> Engine: unknown}"
WARN [10-12|09:39:43.078] Ethash used in fake mode 
INFO [10-12|09:39:43.078] Initialising Ethereum protocol           versions="[63 62]" network=19
INFO [10-12|09:39:43.080] Loaded most recent local header          number=0 hash=131599…ff6994 td=64
INFO [10-12|09:39:43.080] Loaded most recent local full block      number=0 hash=131599…ff6994 td=64
INFO [10-12|09:39:43.080] Loaded most recent local fast block      number=0 hash=131599…ff6994 td=64
INFO [10-12|09:39:43.081] Regenerated local transaction journal    transactions=0 accounts=0
INFO [10-12|09:39:43.081] Starting P2P networking 
INFO [10-12|09:39:43.083] RLPx listener up                         self="enode://16cfb2a7566f5eed064266e71c3a75840c5168995d2b94adde1e87facf55fecb3fa1fe7cbaf3331e34ffea286765a1ce88c23d1cf8e39a06e05d55faaf6e147b@[::]:30303?discport=0"
INFO [10-12|09:39:43.090] IPC endpoint opened                      url=/travis/geth.ipc
INFO [10-12|09:39:43.092] HTTP endpoint opened                     url=http://0.0.0.0:8545 cors= vhosts=localhost
E[10-12|09:39:52.778] Connection failed @ recvRoutine (reading byte) module=p2p peer=18.220.30.167:26656 conn=MConn{18.220.30.167:26656} err=EOF
E[10-12|09:39:52.779] Stopping peer for error                      module=p2p peer="Peer{MConn{18.220.30.167:26656} ae59c403205ae5893a7041b8be04694e915754b0 out}" err=EOF
E[10-12|09:39:53.808] Connection failed @ recvRoutine (reading byte) module=p2p peer=18.220.30.167:26656 conn=MConn{18.220.30.167:26656} err="read tcp 172.17.0.2:59358->18.220.30.167:26656: read: connection reset by peer"
E[10-12|09:39:53.808] Stopping peer for error                      module=p2p peer="Peer{MConn{18.220.30.167:26656} ae59c403205ae5893a7041b8be04694e915754b0 out}" err="read tcp 172.17.0.2:59358->18.220.30.167:26656: read: connection reset by peer"
E[10-12|09:39:53.919] Connection failed @ recvRoutine (reading byte) module=p2p peer=18.191.158.191:26656 conn=MConn{18.191.158.191:26656} err=EOF
E[10-12|09:39:53.919] Stopping peer for error                      module=p2p peer="Peer{MConn{18.191.158.191:26656} d19ae8fadf52b0f329ecde51c805683558294a6c out}" err=EOF
E[10-12|09:40:07.636] SendTimeout                                  module=blockchain peer=ae59c403205ae5893a7041b8be04694e915754b0 reason="peer did not send us anything" timeout=15s
E[10-12|09:40:08.240] SendTimeout                                  module=blockchain peer=ae59c403205ae5893a7041b8be04694e915754b0 reason="peer did not send us anything" timeout=15s
E[10-12|09:40:08.642] SendTimeout                                  module=blockchain peer=d19ae8fadf52b0f329ecde51c805683558294a6c reason="peer did not send us anything" timeout=15s
E[10-12|09:40:23.878] Connection failed @ recvRoutine (reading byte) module=p2p peer=18.220.30.167:26656 conn=MConn{18.220.30.167:26656} err=EOF
E[10-12|09:40:23.879] Stopping peer for error                      module=p2p peer="Peer{MConn{18.220.30.167:26656} ae59c403205ae5893a7041b8be04694e915754b0 out}" err=EOF
E[10-12|09:40:38.635] SendTimeout                                  module=blockchain peer=ae59c403205ae5893a7041b8be04694e915754b0 reason="peer did not send us anything" timeout=15s
E[10-12|09:41:23.478] Connection failed @ recvRoutine (reading byte) module=p2p peer=18.191.158.191:26656 conn=MConn{18.191.158.191:26656} err=EOF
E[10-12|09:41:23.478] Stopping peer for error                      module=p2p peer="Peer{MConn{18.191.158.191:26656} d19ae8fadf52b0f329ecde51c805683558294a6c out}" err=EOF


What difference will it make if i pull the image again? Because that's the only thing that i didn't follow while starting afresh. 
OS : Ubuntu 
OS-type: 64 bit
Ram: 8GB
DISK: 983.4 GB

**Comment by tpmccallum** [comment]
With the knowledge that my latest installation (which I did after this issue was opened) did a fresh pull for the image (cybermiles/travis:latest) I would say that pulling the latest image would make the difference.
Let me know how this goes for you.

**Comment by tpmccallum** [comment]
👍
Fantastic, looks like everything is working, congratulations!
You can now start a console and interact with the blockchain.

Get the IP address of the travis node
```
docker inspect -f '{{ .NetworkSettings.IPAddress }}' travis
```
```
172.17.0.2
```
Use the IP address from above to connect
```
docker run --rm -it cybermiles/travis attach http://172.17.0.2:8545
```
Once you are inside the console, you can type cmt.syncing to see if you are still syncing (true) or not (false); as shown below.
```
> cmt.syncing
{
  catching_up: false,
  latest_app_hash: "B376053146D5A12C8ADAE71261811D2AC3668C07",
  latest_block_hash: "297BD6DF3BE6C47CB4C1E952545DAF8DD334112C",
  latest_block_height: 12345,
  latest_block_time: "2018-09-05T00:08:51.831965507Z"
}
```

Let us know how this goes and feel free to reach out if you need anything else 

Kind regards 
Tim
