### ISSUE TITLE
This service crashed when I ran 'personal.unlockAccount' multiple times.

### ISSUE THREAD

**Issue by xxlunch** [CyberMiles/travis#16]
I think the cause of this problem is insufficient memory, but I have allocated 2G memory.
environment ： Linux on windows with Oracle VM VirtualBox
![qq20181015-0](https://user-images.githubusercontent.com/44078281/46944716-62c41900-d0a5-11e8-8f2c-f8bf88e01f39.png)

**Comment by maggie-wang-bbt** [comment]
Accessing a key file requires 256MB of memory to decrypt, according to https://github.com/ethereum/go-ethereum/issues/17417. 
Also check this: https://github.com/ethereum/go-ethereum/issues/17604, maybe it's similar to yours.
