### ISSUE TITLE
Problem Attaching Travis Javascript Console in Docker

### ISSUE THREAD

**Issue by p0p3yee** [CyberMiles/travis#19]
I followed this [Tutorial](https://travis.readthedocs.io/en/latest/connect-mainnet.html) to setup docker and running travis on it.

First, I executed this command: `docker run --name travis -v $HOME/.travis:/travis -t -p 26657:26657 cybermiles/travis:v0.1.2-beta node start --home /travis`

and then i exectue: `docker run --rm -it cybermiles/travis:v0.1.2-beta attach http://172.17.0.2:8545`, 

I got this error: ```Fatal: Failed to start the JavaScript console: api modules: Post http://172.17.0.2:8545: dial tcp 172.17.0.2:8545: connect: connection refused```

I also tried to run the docker by following command: `docker run --name travis -v $HOME/.travis:/travis -t -p 8545:8545 cybermiles/travis:v0.1.2-beta node start --home /travis`. But still, the same error occur.

I already set `rpc = true` in `config.toml`, and it is still not working. I also tried to attach:
1. `http://localhost:8545`
2. `http://localhost:26657`
3. `http://172.17.0.2:26657`

None of the above addresses work. However, i can connect to port 26657 on browser

The travis is running and already downloaded all the block.

**This problem only happen in Docker, it works fine if i build from source.**

Screenshots:
![image](https://user-images.githubusercontent.com/40417611/47549768-a7ff0b00-d92f-11e8-9ecd-1436f328634b.png)

Any idea how can i fix this ? thanks.

**Comment by tpmccallum** [comment]
What is the result of 
```
netstat -at
```

**Comment by tpmccallum** [comment]
What is the result of 
```
docker ps
```

**Comment by maggie-wang-bbt** [comment]
@1tD0g Please update `rpcaddr` in `config.toml` to `0.0.0.0`, and restart the container.

**Comment by maggie-wang-bbt** [comment]
close for now, please re-open if still not right.
