### ISSUE TITLE
Invalid nonce when broadcasting to network.

### ISSUE THREAD

**Issue by ZebPayDhruvil** [CyberMiles/travis#28]
Trying to send a cmt transaction on Testnet.

Raw transaction : 
**f86c03850165a0bc0082520894dad74cae49a0783f1f53b45a7ff0ee4219b2b6a28805e7c02f7cd30000804aa03aa0aeb6132ffd58aae720679a629bbee5ca79579edf79dfa40229d2b903a616a00c98d452bf9ced560ca2d375a2542d76846cd083e76ecf63699c2b1dfc686ce9**

Using 
  **let nonce = "0x" + await web3.cmt.getTransactionCount(myAddress, "pending").toString(16);**
to get the nonce
Upon checking cmt explorer it seems correct.

Upon using
 **web3.cmt.sendRawTransaction(rawTx)**

it returns 
**Error: code:6 log:"Nonce not strictly increasing. Expected 0 Got 3" fee:<>**

Which seems to be problem, btw when I checked it few weeks ago , it use to work.

**Comment by maggie-wang-bbt** [comment]
Is 0x9867e6EAb0E9Cb5789285c90E7775C3fDe5D85bf your address? getTransactionCount returns 0 for that address, but you used nonce=3 in rawTx.

**Comment by ZebPayDhruvil** [comment]
No, my address is 
**0x9cff26b9d7ba89e34a3b7105418e149d660af019**
`var Web3 = require('web3-cmt');
var Tx = require('ethereumjs-tx');
var async = require('async');

var web3 = new Web3(new Web3.providers.HttpProvider('https://testnet.cmtwallet.io:8545'));
async function sign(destAddress, nonce, privKey) {
    return new Promise(async function (resolve, reject) {
        // let id = await web3.cmt.getTransaction('0xed7a2465cdf959c5018a8864bdb8ee90e468de4f367d7b336575e9f805b54c36')
        let id = web3.version.network;
        console.log('ID', id);

        var gasPriceGwei = 6;
        var gasLimit = 21000;
        // Chain ID of Ropsten Test Net is 3, replace it to 1 for Main Net
        var chainId = id;
        var rawTransaction = {
            // "from": myAddress,
            "nonce": nonce,
            "gasPrice": web3.toHex(gasPriceGwei * 1e9),
            "gasLimit": web3.toHex(gasLimit),
            "to": destAddress,
            "value": 425520000000000000,
            //  "data": contract.methods.transfer(destAddress, transferAmount).encodeABI(),
            "chainId": chainId
        };

        //console.log(`Raw of Transaction: \n${JSON.stringify(rawTransaction, null, '\t')}\n------------------------`);
        // The private key for myAddress in .env

        var tx = new Tx(rawTransaction);
        tx.sign(privKey);
        console.log(tx.getSenderAddress().toString('hex'))
        var serializedTx = tx.serialize();

        return resolve(serializedTx.toString('hex'));
    });
}

// Create an async function so I can use the "await" keyword to wait for things to finish
async function main(destAddress) {


    try {
        console.log('***********************');
        console.log('Sending to ', destAddress);
        var myAddress = "0x9cff26b9d7ba89e34a3b7105418e149d660af019";

        let nonce = "0x" + await web3.cmt.getTransactionCount(myAddress, "pending").toString(16);
        //nonce is incorrect in case of pending transaction
        console.log('NONCE :', nonce);
        var privKey = new Buffer('3d9d49f6c884b47836435d089da07b52004e678b2a4c64a9be187f652bfb97a1', 'hex');
        let signed = await sign(destAddress, nonce, privKey);
        console.log('Signed  :', signed);
        let rawTx = signed.startsWith('0x') ? signed : '0x' + signed;
        let t = await web3.cmt.sendRawTx(rawTx)
        console.log('BB', t);
        return t;
    } catch (e) {
        console.error(e);
    }

}


addre = [
    "0xDad74cAE49A0783f1F53b45a7fF0EE4219b2b6a2",
    "0x1d8c6c82687Dd4235Fc8D957CA8B3DA0d261D484",
    "0x603Eb8348f4A85675b5a1F8A5bA563e9a8F9c2cd",
    "0x868A23f9Ce41639a076BfcC7251c2B8EF0524f5a",
    "0xD62211C26De39d83eFf59eBbA342065174c8dbcf",
    "0x0d89d74747A3357DF6B91B232917a3038EBD7760",
    "0xF66DfB46Ab17c14e3e7E4941B3CF41E6eB3cc1ae",
    "0x6739703a97861CF07EB04bCF3F131397AF3b3C50",
    "0x1e4ad3154AE2185aA88E05eABd037D3deaDff1F9",
    "0xf9183704bC587Dec71b5804B94cb03925eA509c7"

]





async.timesSeries(addre.length,
    function (n, next) {
        main(addre[n])
            .then(v => {
                console.log(v);
                SleepForseconds(next, 'Sleeping....');
            }).catch(err => {
                console.error('ERR', err);
                //    next()
            });
    }, function (err, txids) {
        console.log(txids);
    });

process.on('unhandledRejection', (err) => {
    console.error(err)
});


function SleepForseconds(next, msg) {
    console.log(msg);
    setTimeout(function () {
        next();
    }, 10000);
}

`


Entire code

**Comment by maggie-wang-bbt** [comment]
I got **0x9867e6EAb0E9Cb5789285c90E7775C3fDe5D85bf** from the raw transaction in your first comment. So something must be wrong when you signed the transaction.

Look into your code, `chainId` is number, but web3.version.network returns a string. Please use `let id = Number(web3.version.network)` or `let id = web3.net.id`.

**Comment by ZebPayDhruvil** [comment]
After setting networkid to  web3.net.id
It worked thanks
Closing issue
