### ISSUE TITLE
Error starting proxy app connections: Error on replay: Wrong Block.Header.AppHash.

### ISSUE THREAD

**Issue by zwtaa** [CyberMiles/travis#29]
The operating system is Ubuntu. The process of the main chain node automatically dies, and the error is reported after restart. 
 Error starting proxy app connections: Error on replay: Wrong Block.Header.AppHash.  Expected 8CD045206132A962122215E0F3F33F2F2EC52362, got EFA93D8C4BC214017919870357E94C4296FA5CB6 ，
How to solve such problems？
![1544433993 1](https://user-images.githubusercontent.com/38554130/49722957-d139e780-fca0-11e8-9265-aaec261c0339.jpg)

**Comment by juntao** [comment]
This is the block height where all validator nodes switched to hotfix2. I would recommend two things:

1 Restart your service with the hotfix2 software.

And if that does not work

2 Start the node again from a more recent snapshot.

https://travis.readthedocs.io/en/latest/connect-mainnet.html#snapshot





-----------------------------
Michael Yuan, PhD
http://www.michaelyuan.com

________________________________
