### ISSUE TITLE
Tendermint state.AppHash does not match AppHash after replay.

### ISSUE THREAD

**Issue by burnside** [CyberMiles/travis#31]
```
INFO [01-19|14:14:24.672] Imported new chain segment               blocks=1 txs=0 mgas=0.000 elapsed=399.145µs mgasps=0.000 number=747995 hash=141dec…834579 cache=349.85kB
INFO [01-19|14:14:33.794] Imported new chain segment               blocks=1 txs=0 mgas=0.000 elapsed=444.554µs mgasps=0.000 number=747996 hash=dc420c…df8bf2 cache=349.85kB
INFO [01-19|14:14:46.315] Imported new chain segment               blocks=1 txs=0 mgas=0.000 elapsed=592.318µs mgasps=0.000 number=747997 hash=6bc554…46125c cache=349.85kB
^Ccaptured interrupt, exiting...
INFO [01-19|14:14:56.848] Got interrupt, shutting down...
INFO [01-19|14:14:56.851] HTTP endpoint closed                     url=http://localhost:8546
INFO [01-19|14:14:56.854] IPC endpoint closed                      endpoint=/home/cybermiles/.travis/cybermiles.ipc
INFO [01-19|14:14:56.856] Writing cached state to disk             block=747997 hash=6bc554…46125c root=ed62d1…52e4fd
INFO [01-19|14:14:56.858] Persisted trie from memory database      nodes=6 size=2.33kB time=1.041672ms gcnodes=1188 gcsize=460.94kB gctime=6.668894ms livenodes=769 livesize=297.98kB
INFO [01-19|14:14:56.859] Writing cached state to disk             block=747996 hash=dc420c…df8bf2 root=990f55…25c352
INFO [01-19|14:14:56.859] Persisted trie from memory database      nodes=6 size=2.33kB time=192.414µs  gcnodes=0    gcsize=0.00B    gctime=0s         livenodes=763 livesize=295.66kB
INFO [01-19|14:14:56.859] Writing cached state to disk             block=747870 hash=dd2921…c1ff39 root=e9e8d1…9311fb
INFO [01-19|14:14:56.860] Persisted trie from memory database      nodes=6 size=2.33kB time=201.237µs  gcnodes=0    gcsize=0.00B    gctime=0s         livenodes=757 livesize=293.33kB
INFO [01-19|14:14:56.864] Blockchain manager stopped
INFO [01-19|14:14:56.864] Transaction pool stopped
INFO [01-19|14:14:56.869] Database closed                          database=/home/cybermiles/.travis/vm/chaindata
E[01-19|22:14:57.857] RPC HTTP server stopped                      module=rpc-server err="accept tcp [::]:26657: use of closed network connection"
INFO [01-19|14:14:57.859] Sqlite db closed successfully！
```
then on subsequent restart:
```
$ cybermiles/start.sh
INFO [01-19|14:45:08.427] Maximum peer count                       ETH=25 LES=0 total=25
INFO [01-19|14:45:08.433] Starting peer-to-peer node               instance=vm/v1.8.12-stable/linux-amd64/go1.10.3
INFO [01-19|14:45:08.434] Allocated cache and file handles         database=/home/cybermiles/.travis/vm/chaindata cache=768 handles=512
INFO [01-19|14:45:08.821] Initialised chain configuration          config="{ChainID: 18 Homestead: 0 DAO: 0 DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Engine: ethash}"
WARN [01-19|14:45:08.821] Ethash used in fake mode
INFO [01-19|14:45:08.859] Initialising Ethereum protocol           versions="[63 62]" network=18
INFO [01-19|14:45:09.011] Loaded most recent local header          number=747997 hash=6bc554…46125c td=11161782357656522522869753689572390267243864405453424476254122530128932149461339591642732426123238505380105693048804594002286274821213849764055714839918367637194959161665482
INFO [01-19|14:45:09.012] Loaded most recent local full block      number=747997 hash=6bc554…46125c td=11161782357656522522869753689572390267243864405453424476254122530128932149461339591642732426123238505380105693048804594002286274821213849764055714839918367637194959161665482
INFO [01-19|14:45:09.012] Loaded most recent local fast block      number=747997 hash=6bc554…46125c td=11161782357656522522869753689572390267243864405453424476254122530128932149461339591642732426123238505380105693048804594002286274821213849764055714839918367637194959161665482
INFO [01-19|14:45:09.023] Loaded local transaction journal         transactions=0 dropped=0
INFO [01-19|14:45:09.023] Regenerated local transaction journal    transactions=0 accounts=0
WARN [01-19|14:45:09.024] Blockchain not empty, fast sync disabled
INFO [01-19|14:45:09.027] Starting P2P networking
INFO [01-19|14:45:09.029] RLPx listener up                         self="enode://05552faa56d9a99fc35f5666b1366e525ae57e7dcb4c59485bbaa98c6aa0763d317bd24e537f858d21550591bedfe2d836279bace2c00c66f0247c81929efd73@[::]:30333?discport=0"
INFO [01-19|14:45:09.039] Mapped network port                      proto=tcp extport=30333 intport=30333 interface=NAT-PMP(192.168.1.1)
INFO [01-19|14:45:09.046] IPC endpoint opened                      url=/home/cybermiles/.travis/cybermiles.ipc
INFO [01-19|14:45:09.052] HTTP endpoint opened                     url=http://localhost:8546                   cors= vhosts=localhost
panic: Tendermint state.AppHash does not match AppHash after replay. Got 1B811EBDB062C018C26854BA70EAA92046DABAF1, expected 85274A3D577AF02558C87522BCD66C64FC8C427B

goroutine 1 [running]:
github.com/CyberMiles/travis/vendor/github.com/tendermint/tendermint/consensus.checkAppHash(0xc437c4a3a0, 0xa, 0xb69de, 0xa6db, 0xc4227fcf40, 0x14, 0x14, 0x1, 0xc4227fd040, 0x14, ...)
        /go/src/github.com/CyberMiles/travis/vendor/github.com/tendermint/tendermint/consensus/replay.go:426 +0x1c7
github.com/CyberMiles/travis/vendor/github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc420bff7c0, 0xc437c4a3a0, 0xa, 0xb69de, 0xa6db, 0xc4227fcf40, 0x14, 0x14, 0x1, 0xc4227fd040, ...)
        /go/src/github.com/CyberMiles/travis/vendor/github.com/tendermint/tendermint/consensus/replay.go:328 +0x3ef
github.com/CyberMiles/travis/vendor/github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc420bff7c0, 0x19c0540, 0xc439021400, 0x4, 0x19b3580)
        /go/src/github.com/CyberMiles/travis/vendor/github.com/tendermint/tendermint/consensus/replay.go:246 +0x3e5
github.com/CyberMiles/travis/vendor/github.com/tendermint/tendermint/proxy.(*multiAppConn).OnStart(0xc439021400, 0xc42277ef00, 0x15)
        /go/src/github.com/CyberMiles/travis/vendor/github.com/tendermint/tendermint/proxy/multi_app_conn.go:108 +0x527
github.com/CyberMiles/travis/vendor/github.com/tendermint/tendermint/libs/common.(*BaseService).Start(0xc439021400, 0x0, 0x0)
        /go/src/github.com/CyberMiles/travis/vendor/github.com/tendermint/tendermint/libs/common/service.go:130 +0x3bd
github.com/CyberMiles/travis/vendor/github.com/tendermint/tendermint/node.NewNode(0xc4201e3d40, 0x19b5480, 0xc4255802d0, 0x199eae0, 0xc4363c13c0, 0xc43139b130, 0x1869558, 0x1869560, 0x19b3580, 0xc43655b740, ...)
        /go/src/github.com/CyberMiles/travis/vendor/github.com/tendermint/tendermint/node/node.go:187 +0x693
github.com/CyberMiles/travis/server/commands.startTendermint(0x19bba80, 0xc444cd0270, 0xc4200d2d20, 0xc423c221c0, 0xc43c2e0000)
        /go/src/github.com/CyberMiles/travis/server/commands/services.go:237 +0x278
github.com/CyberMiles/travis/server/commands.startServices(0x7ffee1987617, 0x18, 0xc4200d2d20, 0xb69de, 0xb69de, 0xc434f9f690)
        /go/src/github.com/CyberMiles/travis/server/commands/services.go:67 +0x34b
github.com/CyberMiles/travis/server/commands.start(0x7ffee1987617, 0x18, 0xc4200d2d20, 0x2b, 0x2710)
        /go/src/github.com/CyberMiles/travis/server/commands/start.go:100 +0x7a
github.com/CyberMiles/travis/server/commands.startCmd.func1(0xc420856780, 0xc42002a900, 0x0, 0x2, 0x0, 0x0)
        /go/src/github.com/CyberMiles/travis/server/commands/start.go:75 +0x37d
github.com/CyberMiles/travis/vendor/github.com/spf13/cobra.(*Command).execute(0xc420856780, 0xc42002a520, 0x2, 0x2, 0xc420856780, 0xc42002a520)
        /go/src/github.com/CyberMiles/travis/vendor/github.com/spf13/cobra/command.go:762 +0x468
github.com/CyberMiles/travis/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x247bb60, 0x1616342, 0x24, 0xc42049fd37)
        /go/src/github.com/CyberMiles/travis/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/CyberMiles/travis/vendor/github.com/spf13/cobra.(*Command).Execute(0x247bb60, 0xc42002a040, 0x247bc50)
        /go/src/github.com/CyberMiles/travis/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/CyberMiles/travis/vendor/github.com/tendermint/tendermint/libs/cli.Executor.Execute(0x247bb60, 0x186a200, 0x2, 0xc4204b6900)
        /go/src/github.com/CyberMiles/travis/vendor/github.com/tendermint/tendermint/libs/cli/setup.go:89 +0x4e
main.main()
        /go/src/github.com/CyberMiles/travis/cmd/travis/main.go:48 +0x132
```
Do I have to re-install my node now?  Or is there a way to recover from this corruption?  (And somehow prevent future corruption?)

Cheers

**Comment by burnside** [comment]
> Looks like your local travis db is corrupted. Please kill travis gracefully via `kill [pid]` or ctrl+c, and wait until the travis pid is truly destroyed.

You can see in the logs provided it was killed with CTRL+C and there was a 30 minute gap between the kill and subsequent restart.  (I shut it down to take a consistent backup)  If it weren't a clean stop I would not have made the report.

> You can recover from latest snapshot: https://travis.readthedocs.io/en/latest/connect-mainnet.html#snapshot.

Thanks, I have done that.  I am concerned this will happen again.  Recovery from snapshot takes an excessive amount of bandwidth and time and will only get worse as the blockchain grows.

> Also noticed that your server's timezone is UTC-8, you'd better set it to UTC.

This is a desktop PC.  :/  What effect does the system timezone have on Travis?

Thanks!

**Comment by maggie-wang-bbt** [comment]
Usually this error won't occur if you shut down gracefully and leave the travis data directory untouched. We have restarted our nodes many times without problem. How did you take the consistent backup, is it possible that one or more db files are corrupted then?

Can you please try restart more times on your side? It would be helpful if you can write down the steps to reproduce the issue.

As to the time zone, your desktop pc can leave it as is. Servers provided by the cloud platform(AWS, GCP etc.) usually set to the UTC time zone by default. We recommend UTC but also works on others.

**Comment by burnside** [comment]
> Usually this error won't occur if you shut down gracefully and leave the travis data directory untouched. We have restarted our nodes many times without problem.

I agree.  I too have restarted this node many times.  Perhaps there is a clue in here somewhere?

> panic: Tendermint state.AppHash does not match AppHash after replay. Got 1B811EBDB062C018C26854BA70EAA92046DABAF1, expected 85274A3D577AF02558C87522BCD66C64FC8C427B

> How did you take the consistent backup, is it possible that one or more db files are corrupted then?

rsync -av --delete /home/cybermiles/.travis/ /srv/backup/home/cybermiles/.travis/

Corruption with the above command is highly unlikely.  Much more likely to have been something that happened during shutdown.

> Can you please try restart more times on your side? It would be helpful if you can write down the steps to reproduce the issue.

The steps are in the log above.  CTRL-C a running Travis.  Wait 30 mins.  Start it again.
I will try to keep a copy of the db next time it happens.  I purged this one due to storage constraints on my ssd.

In the meantime, can you look into these?

https://github.com/cosmos/ethermint/issues/397#issuecomment-377109954 (discussion)

https://github.com/urugang/ethermint/commit/ff186526393ab25302bb3975aeac0714c36eb9ef (commit)

https://github.com/CyberMiles/travis/blob/develop/app/ethereum.go (line 93)

https://github.com/urugang/ethermint/blob/ff186526393ab25302bb3975aeac0714c36eb9ef/app/app.go (line 83)

Per their discussion it doesn't appear the patch completely fixes it, but does make it better.  I don't understand it at all, so I can't comment on it.  Just trying to help.

Cheers.

**Comment by maggie-wang-bbt** [comment]
> In the meantime, can you look into these?

Thanks for your information. Those are old threads, go-ethereum changed a lot since then, `blockchain.LastBlockHash()` no longer exists in recent version. We are using `currentBlock.Hash()`, similar logic, as you can see from old version go-ethereum: https://github.com/ethereum/go-ethereum/blob/v1.5.7/core/blockchain.go#L296. 

> The steps are in the log above. CTRL-C a running Travis. Wait 30 mins. Start it again.
I will try to keep a copy of the db next time it happens. I purged this one due to storage constraints on my ssd.

I'm trying to figure out what makes this time different, unfortunately, following those steps still can't help me reproduce the issue on my side. Anyway, it does help if you could keep a db copy next time. Thanks a lot.

**Comment by burnside** [comment]
> I'm trying to figure out what makes this time different, unfortunately, following those steps still can't help me reproduce the issue on my side. Anyway, it does help if you could keep a db copy next time. Thanks a lot.

Thanks, much appreciated!

A thought: even if you can't figure out what is causing the corruption on close, maybe detection and recovery can be built in?  Eg, purge the most recent blocks from the db and retry?

Cheers.

**Comment by maggie-wang-bbt** [comment]
I like your thoughts. In fact we had some internal discussion on it too, but couldn't find a way to implement yet. That's why we're currently suggesting `snapshot and replay` to recover from a crash.
