### ISSUE TITLE
Does Cybermiles will temp fork or nerver fork?

### ISSUE THREAD

**Issue by leeduckgo** [CyberMiles/travis#35]
The consensus is "Tendermint for BFT consensus", so I think there is not temp fork, but the confirmation of huobi.pro is 30 blocks, so I would like to confirm this.

**Comment by juntao** [comment]
CyberMiles is instant finality. Every block is final. There is no need to wait for 30 blocks.



-----------------------------
Michael Yuan, PhD
http://www.michaelyuan.com

________________________________

**Comment by leeduckgo** [comment]
thx a lot
